server:
  port: 8201
spring:
  application:
    name: userAuthService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.9:3306/test
    username: root
    password: 123456
  redis:
    host: 192.168.31.9
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.9:8848
springfox:
  documentation:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
